### ISSUE TITLE
项目

### ISSUE THREAD

**Issue by gong-yangeng** [huccct/react-admin#1]
项目打不开

**Comment by huccct** [comment]
有报错吗

**Comment by huccct** [comment]
这个repo是 react-admin, vue-admin 打不开 挂个 科学上网

**Comment by gong-yangeng** [comment]
react-admin打不开

**Comment by gong-yangeng** [comment]
![Uploading 31ad74336d0102000193c8e6a308f6c.png…]()

**Comment by huccct** [comment]
有报错吗 报错截个图 不然我也看不出来 我这边OK的

**Comment by gong-yangeng** [comment]
![31ad74336d0102000193c8e6a308f6c](https://github.com/huccct/react-admin/assets/145740801/3eccda7a-43b9-42e4-86cb-493df3242f54)

**Comment by gong-yangeng** [comment]
大佬，你看看

**Comment by huccct** [comment]
看上去应该是版本问题
![image](https://github.com/huccct/react-admin/assets/87902123/0f13c09c-61da-4013-bcb8-3f611a8ebf01)

**Comment by gong-yangeng** [comment]
我看一下

**Comment by gong-yangeng** [comment]
还是不行
![62d930e5728fe9bd44c534eaae476ad](https://github.com/huccct/react-admin/assets/145740801/871c3866-4ffa-4d07-8074-49d64651f201)

**Comment by gong-yangeng** [comment]
不是版本问题o(╥﹏╥)o

**Comment by huccct** [comment]
pnpm instal pnpm run dev 或者重新fork一下， 不行的话晚点给你看看

**Comment by gong-yangeng** [comment]
好的

**Comment by gong-yangeng** [comment]
还是不行，麻烦你了，大佬

**Comment by huccct** [comment]
方便给个联系方式吗

**Comment by gong-yangeng** [comment]
gyg2979427502:微信
